# Vim is Vim 
[[link]]
source = 'vim/vimrc'
target.windows = '~/vimfiles/vimrc'
target.unix = '~/.config/vim/vimrc'
[[link]]
source = 'vim/gvimrc'
target.windows = '~/vimfiles/gvimrc'
target.unix = '~/.config/vim/gvimrc'

# Just a Text Vim filetype plugin
# TODO: Should be separated to other repository
[[link]]
source = 'vim/jat'
target.windows = '~/vimfiles/pack/site/start/jat'
target.unix = '~/.config/vim/pack/site/start/jat'

# Vocabulary files support
# TODO: This is temporary
[[link]]
source = 'vim/voc'
target.windows = '~/vimfiles/pack/site/start/voc'
target.unix = '~/.config/vim/pack/site/start/voc'

[[link]]
source = 'ranger/rc.conf'
target.unix = '~/.config/ranger/rc.conf'

# fish shell configuration and functions files
[[link]]
source = 'fish/config.fish'
target.unix = '~/.config/fish/config.fish'
[[link]]
source = 'fish/functions/fish_prompt.fish'
target.unix = '~/.config/fish/functions/fish_prompt.fish'
[[link]]
source = 'fish/functions/fish_greeting.fish'
target.unix = '~/.config/fish/functions/fish_greeting.fish'
[[link]]
source = 'fish/functions/vims.fish'
target.unix = '~/.config/fish/functions/vims.fish'
[[link]]
source = 'fish/functions/l.fish'
target.unix = '~/.config/fish/functions/l.fish'

# tmux configuration
[[link]]
source = 'tmux/tmux.conf'
target.unix = '~/.config/tmux/tmux.conf'

# OMG, it's PowerShell
[[link]]
source = 'powershell/Microsoft.PowerShell_profile.ps1'
target.windows = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

# Emacs
[[link]]
source = 'emacs/init.el'
target.windows = "~/.emacs.d/init.el"
target.unix = "~/.config/emacs/init.el"
[[link]]
source = 'emacs/early-init.el'
target.windows = "~/.emacs.d/early-init.el"
target.unix = "~/.config/emacs/early-init.el"
