[[link]]
source = 'vim/vimrc'
target.windows = '~/vimfiles/vimrc'
target.unix = '~/.vim/vimrc'

[[link]]
source = 'vim/gvimrc'
target.windows = '~/vimfiles/gvimrc'

[[link]]
source = 'vim/jat'
target.windows = '~/vimfiles/pack/site/start/jat'
target.unix = '~/.vim/pack/site/start/jat'

[[link]]
source = 'ranger/rc.conf'
target.unix = '~/.config/ranger/rc.conf'

[[link]]
source = 'fish/config.fish'
target.unix = '~/.config/fish/config.fish'

[[link]]
source = 'tmux/tmux.conf'
target.unix = '~/.tmux.conf'

[[link]]
source = 'powershell/Microsoft.PowerShell_profile.ps1'
target.windows = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
