# Vim
# [[link]]
# source = 'vim/vimrc'
# target.windows = '~/vimfiles/vimrc'
# target.unix = '~/.config/vim/vimrc'
# [[link]]
# source = 'vim/gvimrc'
# target.windows = '~/vimfiles/gvimrc'
# target.unix = '~/.config/vim/gvimrc'

# Vim9 
[[link]]
source = 'vim9/vimrc'
target.unix = '~/.config/vim/vimrc'
target.windows = '~/vimfiles/vimrc'
[[link]]
source = 'vim9/kiso.vim'
target.unix = '~/.config/vim/autoload/kiso.vim'
target.windows = '~/vimfiles/autoload/kiso.vim'
[[link]]
source = 'vim9/hako.vim'
target.unix = '~/.config/vim/autoload/hako.vim'
target.windows = '~/vimfiles/autoload/hako.vim'

# ranger
[[link]]
source = 'ranger/rc.conf'
target.unix = '~/.config/ranger/rc.conf'

# fish shell
[[link]]
source = 'fish/config.fish'
target.unix = '~/.config/fish/config.fish'
[[link]]
source = 'fish/functions/fish_prompt.fish'
target.unix = '~/.config/fish/functions/fish_prompt.fish'
[[link]]
source = 'fish/functions/fish_greeting.fish'
target.unix = '~/.config/fish/functions/fish_greeting.fish'
[[link]]
source = 'fish/functions/vims.fish'
target.unix = '~/.config/fish/functions/vims.fish'
[[link]]
source = 'fish/functions/l.fish'
target.unix = '~/.config/fish/functions/l.fish'

# tmux
[[link]]
source = 'tmux/tmux.conf'
target.unix = '~/.config/tmux/tmux.conf'

# PowerShell
[[link]]
source = 'powershell/Microsoft.PowerShell_profile.ps1'
target.windows = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

# Emacs
[[link]]
source = 'emacs/init.el'
target.unix = "~/.config/emacs/init.el"
target.windows = "~/.emacs.d/init.el"
