[meta]
default_tags = ['vim_saishin']

# Vim Juurai (従来)
[[link]]
source = 'vim/juurai/vimrc'
target.windows = '~/vimfiles/vimrc'
target.unix = '~/.config/vim/vimrc'
tag = 'vim_juurai'
[[link]]
source = 'vim/juurai/gvimrc'
target.windows = '~/vimfiles/gvimrc'
target.unix = '~/.config/vim/gvimrc'
tag = 'vim_juurai'

# Vim Saishin (最新)
[[link]]
source = 'vim/saishin/vimrc'
target.unix = '~/.config/vim/vimrc'
target.windows = '~/vimfiles/vimrc'
tag = 'vim_saishin'
[[link]]
source = 'vim/saishin/gvimrc'
target.unix = '~/.config/vim/gvimrc'
target.windows = '~/vimfiles/gvimrc'
tag = 'vim_saishin'
[[link]]
source = 'vim/saishin/kiso.vim'
target.unix = '~/.config/vim/autoload/kiso.vim'
target.windows = '~/vimfiles/autoload/kiso.vim'
tag = 'vim_saishin'
[[link]]
source = 'vim/saishin/hako.vim'
target.unix = '~/.config/vim/autoload/hako.vim'
target.windows = '~/vimfiles/autoload/hako.vim'
tag = 'vim_saishin'

# Emacs
[[link]]
source = 'emacs/init.el'
target.unix = "~/.config/emacs/init.el"
target.windows = "~/.emacs.d/init.el"

# fish shell
[[link]]
source = 'fish/config.fish'
target.unix = '~/.config/fish/config.fish'
[[link]]
source = 'fish/functions/fish_prompt.fish'
target.unix = '~/.config/fish/functions/fish_prompt.fish'
[[link]]
source = 'fish/functions/fish_greeting.fish'
target.unix = '~/.config/fish/functions/fish_greeting.fish'
[[link]]
source = 'fish/functions/vims.fish'
target.unix = '~/.config/fish/functions/vims.fish'
[[link]]
source = 'fish/functions/l.fish'
target.unix = '~/.config/fish/functions/l.fish'

# tmux
[[link]]
source = 'tmux/tmux.conf'
target.unix = '~/.config/tmux/tmux.conf'

# ranger
[[link]]
source = 'ranger/rc.conf'
target.unix = '~/.config/ranger/rc.conf'

# PowerShell
[[link]]
source = 'powershell/Microsoft.PowerShell_profile.ps1'
target.windows = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
